# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: technical-challenge-api
    build: .
    command: challenge run -h 0.0.0.0
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/challenge.db
    volumes:
      - ./challenge:/code/challenge
      - ./db/:/db/
    ports:
      - "5000:5000"
